import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { classifyIssues } from "./lib/fix-rules.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const LOCK_FILE = path.join(__dirname, "auto-fix-lock.json");

function log(msg) {
  console.log(`[auto-fix] ${msg}`);
}

function hasRunToday() {
  try {
    const lock = JSON.parse(fs.readFileSync(LOCK_FILE, "utf-8"));
    const lastRun = new Date(lock.lastRun);
    const today = new Date();
    return lastRun.toDateString() === today.toDateString();
  } catch {
    return false;
  }
}

function markRun() {
  fs.writeFileSync(LOCK_FILE, JSON.stringify({ lastRun: new Date().toISOString() }));
}

function exec(cmd, opts = {}) {
  try {
    return execSync(cmd, { cwd: REPO_ROOT, encoding: "utf-8", timeout: 120000, ...opts });
  } catch (err) {
    return err.stdout || err.message;
  }
}

async function postDiscord(webhookUrl, embeds) {
  if (!webhookUrl) return;
  await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ embeds }),
  });
}

// Model tiers: haiku for mechanical fixes, sonnet for content-aware, opus for deep content generation
const MODELS = {
  haiku: "claude-haiku-4-5-20251001",
  sonnet: "claude-sonnet-4-6",
  opus: "claude-opus-4-6",
};

async function invokeClaude(prompt, model = "haiku") {
  const modelId = MODELS[model] || MODELS.haiku;
  const fullPrompt = `${prompt}\n\nIMPORTANT: A wrong answer is 3x worse than a blank answer. If you are not confident the fix is correct, do not apply it. Just say "SKIPPED: <reason>" and make no changes.`;

  log(`Using model: ${model} (${modelId})`);
  try {
    const result = execSync(
      `npx -y @anthropic-ai/claude-code --print --model ${modelId} "${fullPrompt.replace(/"/g, '\\"')}"`,
      { cwd: REPO_ROOT, encoding: "utf-8", timeout: 300000, env: { ...process.env, PATH: process.env.PATH } }
    );
    return { success: true, output: result };
  } catch (err) {
    return { success: false, output: err.stdout || err.message };
  }
}

function hasChanges() {
  const status = exec("git status --porcelain");
  return status.trim().length > 0;
}

function buildSucceeds() {
  try {
    execSync("npm run build", { cwd: REPO_ROOT, encoding: "utf-8", timeout: 120000 });
    return true;
  } catch {
    return false;
  }
}

async function handleTier1(fix, webhookUrl) {
  log(`Tier 1 fix: ${fix.id} — ${fix.check.name}`);

  const result = await invokeClaude(fix.prompt, fix.model);

  if (result.output.includes("SKIPPED:")) {
    log(`Claude skipped: ${result.output}`);
    return { applied: false, reason: "Claude declined to fix" };
  }

  if (!hasChanges()) {
    log("No changes made.");
    return { applied: false, reason: "No changes detected" };
  }

  if (!buildSucceeds()) {
    log("Build failed after fix. Reverting.");
    exec("git checkout .");
    return { applied: false, reason: "Build failed after fix" };
  }

  exec(`git add -A`);
  exec(`git commit -m "${fix.commitMsg}"`);
  exec(`git push`);
  log("Committed and pushed to main.");

  await postDiscord(webhookUrl, [{
    title: "\u{1F527} Auto-Fix Applied",
    description: `**Category:** ${fix.category}\n**Issue:** ${fix.check.name} — ${fix.check.detail}\n**Fix:** ${fix.commitMsg}\n**Tier:** 1 (auto-committed to main)`,
    color: 3066993,
    timestamp: new Date().toISOString(),
  }]);

  return { applied: true };
}

async function handleTier2(fix, webhookUrl) {
  log(`Tier 2 fix: ${fix.id} — ${fix.check.name}`);

  const branch = `${fix.branchPrefix}-${Date.now()}`;
  exec(`git checkout -b ${branch}`);

  const result = await invokeClaude(fix.prompt, fix.model);

  if (result.output.includes("SKIPPED:")) {
    log(`Claude skipped: ${result.output}`);
    exec("git checkout main");
    exec(`git branch -D ${branch}`);
    return { applied: false, reason: "Claude declined to fix" };
  }

  if (!hasChanges()) {
    log("No changes made.");
    exec("git checkout main");
    exec(`git branch -D ${branch}`);
    return { applied: false, reason: "No changes detected" };
  }

  if (!buildSucceeds()) {
    log("Build failed after fix. Reverting.");
    exec("git checkout .");
    exec("git checkout main");
    exec(`git branch -D ${branch}`);
    return { applied: false, reason: "Build failed after fix" };
  }

  exec(`git add -A`);
  exec(`git commit -m "${fix.commitMsg}"`);
  exec(`git push -u origin ${branch}`);

  // Create PR
  const prBody = `## Auto-Fix\n\n**Category:** ${fix.category}\n**Issue:** ${fix.check.name}\n**Detail:** ${fix.check.detail}\n\nThis PR was automatically generated by the monitoring auto-fix system.\n\n---\n\u{1F916} Generated by DeMar Transportation Auto-Fix`;
  try {
    exec(`gh pr create --title "${fix.commitMsg}" --body "${prBody.replace(/"/g, '\\"')}" --base main`);
    log(`PR created on branch ${branch}.`);
  } catch (err) {
    log(`PR creation failed: ${err}`);
  }

  exec("git checkout main");

  await postDiscord(webhookUrl, [{
    title: "\u{1F4CB} Auto-Fix PR Created",
    description: `**Category:** ${fix.category}\n**Issue:** ${fix.check.name} — ${fix.check.detail}\n**Fix:** ${fix.commitMsg}\n**Branch:** \`${branch}\`\n**Tier:** 2 (PR created for review)`,
    color: 16776960,
    timestamp: new Date().toISOString(),
  }]);

  return { applied: true, branch };
}

async function main() {
  const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    log("ANTHROPIC_API_KEY not set. Skipping auto-fix.");
    return;
  }

  // Rate limit: max one run per day
  if (hasRunToday()) {
    log("Already ran today. Skipping.");
    return;
  }

  // Load scan results
  const resultsArg = process.argv.find(a => a.startsWith("--results="));
  const resultsPath = resultsArg
    ? resultsArg.split("=")[1]
    : path.join(__dirname, "scan-results.json");

  if (!fs.existsSync(resultsPath)) {
    log(`No results file at ${resultsPath}. Skipping.`);
    return;
  }

  const results = JSON.parse(fs.readFileSync(resultsPath, "utf-8"));
  const fixable = classifyIssues(results);

  if (fixable.length === 0) {
    log("No auto-fixable issues found.");
    return;
  }

  log(`Found ${fixable.length} fixable issue(s): ${fixable.map(f => f.id).join(", ")}`);

  // Process Tier 1 first (on main), then Tier 2 (on branches)
  const tier1 = fixable.filter(f => f.tier === 1);
  const tier2 = fixable.filter(f => f.tier === 2);

  for (const fix of tier1) {
    await handleTier1(fix, webhookUrl);
  }

  for (const fix of tier2) {
    await handleTier2(fix, webhookUrl);
  }

  markRun();
  log("Auto-fix run complete.");
}

main().catch((err) => {
  console.error("[auto-fix] Fatal:", err);
  process.exit(1);
});
