// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bskmqpcnidkwulmxywia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJza21xcGNuaWRrd3VsbXh5d2lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMzg3NzgsImV4cCI6MjA4OTgxNDc3OH0.eDCYYB9rFCDM3L2BdfeQBpd4NtJSiXYdhnI2sK09hLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});